### PR TITLE
feat(api): add getSegment function

### PR DESCRIPTION
**Pull request by jpersson**

### CODE REVIEW

**Comment by jpersson** [comment]
@bankyadam thanks for the review! Do you know when the change could be released?

**Comment by bankyadam** [comment]
@jpersson I just wanted to wait another review, but I've merged it now… after the build process finishes, it'll be released on npm with a new version.

**Comment by jpersson** [comment]
@bankyadam 🙏

**Comment by jpersson** [comment]
@bankyadam there is still no new version 😞  would you mind checking if something is up with the build-process?

**Comment by bankyadam** [comment]
There was an error during the build process (on March 1st nsp was shut down).

[v16.1.0](https://github.com/emartech/suite-js-sdk/releases/tag/v16.1.0) is just released.

**Comment by jpersson** [comment]
@bankyadam massive thanks for the quick reply! 👍

**Pull request merged**
