### PR TITLE
I just added the first endpoint for Field API

### PR DESCRIPTION
**Pull request by jzsfkzm**
We'll need it to display and modify personalization information in Content Editor, can you guys merge it?

### CODE REVIEW

**Comment by gergelyke** [comment]
Can you add a test case for the `api/index.js` file as well? After that I am happy to merge & publish

**Comment by jzsfkzm** [comment]
@gergelyke good point, I just added it as well as others

**Comment by gergelyke** [comment]
lastly: from yesterday we decided to go with the angular style of commits - could you rebase your commits using: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md

you can find some example at: https://github.com/RisingStack/graffiti/commits/master

**Comment by jzsfkzm** [comment]
@gergelyke there you are, is this what you think about?

**Comment by gergelyke** [comment]
perfect! :)

**Pull request merged**
